In [2]:
import numpy as np
print(np.__version__)

1.19.2


In [4]:
arr = np.array(42)

print(arr)
print(type(arr))

42
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


Single value = <B>Scalor</B> ex:(5)<Br>
1D Arry: called <B>Vector</B> [ jitni values utni dimentions ] = 1d tensor ex:([5])<Br>
2D Array: <B>Matrix</B> = 2d tensor ex:([[5]])<Br>
(Depth, Row, Column)

In [14]:
np.ones_like((arr))

array([[1, 1, 1],
       [1, 1, 1]])

In [17]:
np.empty(2)

array([-3.44013170e-059,  1.32156421e+298])

In [24]:
a1 = np.arange(1,11)
a1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [25]:
a2 = np.arange(1,11)
a2**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [28]:
print(a1+a2)

[ 2  4  6  8 10 12 14 16 18 20]


In [29]:
a2.reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
a2.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
a2[0] = 999
a2

array([999,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [34]:
resize = a2.resize(5,2)
print(resize)

None


In [36]:
print(a2)

[[999   2]
 [  3   4]
 [  5   6]
 [  7   8]
 [  9  10]]


Index = <B>( : , num )</B> Puts values in a container(list)<Br>
Slice = <B>[ : , : ]</B> Brings as it is values as per their positions

In [38]:
d2array = np.arange(0,25)
d2array.resize(5,5)
d2array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [40]:
d2array[:2,1:]

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

hstack<Br>
vstack<Br>
dstack<Br>